#!/usr/bin/env bash
# Estenio — Install script for Linux & macOS
#
# Usage:   curl -fsSL https://.../install.sh | bash
#          bash install.sh
#
# This script:
#   1. Detects OS (Linux distro or macOS)
#   2. Checks/installs Python 3.10+ (guides user if missing)
#   3. Checks/installs ffmpeg via system package manager
#   4. Creates a virtual environment and installs estenio
#   5. Adds the 'estenio' command to PATH
#
# No root required (uses user-local install paths).

set -euo pipefail

# ── Colors ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

info()    { echo -e "${CYAN}[INFO]${NC}  $*"; }
success() { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; }

# ── OS Detection ────────────────────────────────────────────────────────────
OS="$(uname -s)"
if [ "$OS" = "Darwin" ]; then
    PLATFORM="macos"
elif [ -f /etc/os-release ]; then
    . /etc/os-release
    case "$ID" in
        ubuntu|debian|linuxmint|pop) PLATFORM="debian" ;;
        fedora|rhel|centos|rocky|almalinux) PLATFORM="fedora" ;;
        arch|manjaro|endeavouros) PLATFORM="arch" ;;
        opensuse*) PLATFORM="suse" ;;
        *) PLATFORM="unknown" ;;
    esac
else
    PLATFORM="unknown"
fi

info "Sistema detectado: $OS ($PLATFORM)"

# ── Python check ────────────────────────────────────────────────────────────
PYTHON=""
for candidate in python3.12 python3.11 python3.10 python3; do
    if command -v "$candidate" &>/dev/null; then
        ver=$("$candidate" -c 'import sys; print(sys.version_info[:2])' 2>/dev/null || true)
        if [ "$ver" = "(3, 10)" ] || [ "$ver" = "(3, 11)" ] || [ "$ver" = "(3, 12)" ] || [ "$ver" = "(3, 13)" ]; then
            PYTHON="$candidate"
            break
        fi
    fi
done

if [ -z "$PYTHON" ]; then
    error "Python 3.10+ não encontrado."
    echo ""
    echo "Instale o Python antes de continuar:"
    echo "  Ubuntu/Debian:  sudo apt install python3 python3-pip python3-venv"
    echo "  Fedora:         sudo dnf install python3 python3-pip"
    echo "  Arch:           sudo pacman -S python python-pip"
    echo "  macOS:          brew install python@3.12"
    echo "  Windows:        https://python.org/downloads/"
    exit 1
fi

success "Python encontrado: $($PYTHON --version)"

# ── ffmpeg check ────────────────────────────────────────────────────────────
if command -v ffmpeg &>/dev/null; then
    success "ffmpeg encontrado: $(ffmpeg -version 2>&1 | head -1)"
else
    warn "ffmpeg não encontrado. Instalando..."
    case "$PLATFORM" in
        debian)
            info "sudo apt install -y ffmpeg"
            sudo apt update -qq && sudo apt install -y ffmpeg
            ;;
        fedora)
            info "sudo dnf install -y ffmpeg-free"
            sudo dnf install -y ffmpeg-free || sudo dnf install -y ffmpeg
            ;;
        arch)
            info "sudo pacman -S --noconfirm ffmpeg"
            sudo pacman -S --noconfirm ffmpeg
            ;;
        macos)
            if command -v brew &>/dev/null; then
                info "brew install ffmpeg"
                brew install ffmpeg
            else
                error "Homebrew não encontrado. Instale o ffmpeg manualmente: https://ffmpeg.org"
                exit 1
            fi
            ;;
        *)
            warn "Não foi possível instalar ffmpeg automaticamente para '$PLATFORM'."
            warn "Instale o ffmpeg manualmente: https://ffmpeg.org/download.html"
            ;;
    esac
    success "ffmpeg instalado."
fi

# ── Install estenio ─────────────────────────────────────────────────────────
INSTALL_DIR="${ESTENIO_INSTALL_DIR:-$HOME/.estenio}"
info "Instalando estenio em: $INSTALL_DIR"

# Create directory structure
mkdir -p "$INSTALL_DIR"

# Create virtual environment
if [ ! -d "$INSTALL_DIR/venv" ]; then
    "$PYTHON" -m venv "$INSTALL_DIR/venv"
fi

# Activate and install
# shellcheck disable=SC1091
source "$INSTALL_DIR/venv/bin/activate"

info "Instalando dependências..."
pip install --upgrade pip --quiet
pip install --upgrade yt-dlp --quiet

# Install estenio from source if local, otherwise from GitHub
if [ -f "pyproject.toml" ]; then
    info "Instalando estenio do diretório local..."
    pip install --upgrade --force-reinstall -e . --quiet
else
    info "Instalando estenio do GitHub..."
    pip install --upgrade --force-reinstall --no-cache-dir "git+https://github.com/lucasrodrigges/estenio.git" --quiet
fi

deactivate

# ── Create launcher script ──────────────────────────────────────────────────
LAUNCHER="$INSTALL_DIR/estenio"
cat > "$LAUNCHER" << LAUNCHEREOF
#!/usr/bin/env bash
# Estenio launcher — auto-generated by install.sh
exec "$INSTALL_DIR/venv/bin/estenio" "\$@"
LAUNCHEREOF
chmod +x "$LAUNCHER"

# ── Add to PATH ─────────────────────────────────────────────────────────────
BIN_DIR="$HOME/.local/bin"
mkdir -p "$BIN_DIR"

# Create (or update) symlink
SYMLINK="$BIN_DIR/estenio"
rm -f "$SYMLINK"
ln -sf "$LAUNCHER" "$SYMLINK"

# PATH verification
if ! echo "$PATH" | tr ':' '\n' | grep -qxF "$BIN_DIR"; then
    SHELL_RC=""
    case "$SHELL" in
        */zsh)  SHELL_RC="$HOME/.zshrc" ;;
        */bash) SHELL_RC="$HOME/.bashrc" ;;
        */fish) SHELL_RC="$HOME/.config/fish/config.fish" ;;
    esac
    if [ -n "$SHELL_RC" ]; then
        if ! grep -qF "$BIN_DIR" "$SHELL_RC" 2>/dev/null; then
            echo "export PATH=\"$BIN_DIR:\$PATH\"" >> "$SHELL_RC"
            info "Adicionado $BIN_DIR ao PATH em $SHELL_RC"
        fi
    fi
fi

# ── Done ────────────────────────────────────────────────────────────────────
echo ""
success "Estenio instalado com sucesso!"
echo ""
echo "Para começar, execute:"
echo "  estenio"
echo ""
if [ -n "${SHELL_RC:-}" ]; then
    echo "Ou recarregue seu shell primeiro:"
    echo "  source $SHELL_RC"
    echo ""
fi
